Fixes for current chrome environment
Change a few things to make the userscript work in my chrome setup: (63.0.3239.84 64-bit on windows 10)

* Replace `window.URL` with `window.location.href` again (fixes "uncaught TypeError: window.URL.indexOf is not a function")
* Remove `let response = JSON.parse(xhr.response);` and rename the xhr parameter to response, as the callback is called with the parsed JSON object rather than the raw xhr object.